# Generated by Django 5.2.5 on 2025-08-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_days', models.PositiveIntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('holiday_type', models.CharField(choices=[('PUBLIC', 'Public Holiday'), ('RESTRICTED', 'Restricted Holiday')], max_length=20)),
            ],
        ),
    ]
